### ISSUE TITLE
Not an issue... 

### ISSUE THREAD

**Issue by ejdunn2** [nlx3647/dataset#11]
But I couldn't find a way to at least say "Thanks!!":)

Took me a bit to get the data in correctly (ended up using your second method) but wow, huge help. I'd been doing several of the classes by hand (and I have ALL the books, so no harm, no foul) but being able to just drop the stuff in there has been amazing. And, I hadn't figured out how to do all the cool symbols in the description either, so one again, thanks!

I'd donate you the traditional "cup of coffee", but I don't know how. ;) Anyway, thanks again, and happy gaming!

**Comment by nlx3647** [comment]
Thank you!!!!!!!!!!!
