### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Lspaceship** [nlx3647/dataset#12]
When I try to import this to the Data Editor, I get the following message
'This ZIP archive does not contain a valid Data Set'

**Comment by Flavor6505** [comment]
Same here

**Comment by nlx3647** [comment]
Can you tell me exactly what you're doing? from code, download zip to the message.

**Comment by Lspaceship** [comment]
Unfortunately, I don't exactly remember. I was able to install the dataset
through copying the folder into my CustomData, but the import through
Oggdude's didn't work.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nlx3647** [comment]
Alright, you got the dataset working. Closing this issue.
