### ISSUE TITLE
Propagandist Talent Issue

### ISSUE THREAD

**Issue by AbyssalGod1** [nlx3647/dataset#24]
Propagandist (Diplomant) has Inside Knowledge talent in three places that should have the talent In The Know.

**Comment by HighPriestofZuul** [comment]
It looks like the talent was accidentally erased at some point and for whatever reason it's defaulting to Inside Knowledge instead. This can be fixed relatively easily.

1. Open up the Data Editor (SWCharGenDataEditor)
2. Go to Talents.
3. Paste WITHOUT QUOTES in "In the Know" for Talent Name, "INKNOW" for Talent Key, check the Ranked box, then press Update.
4. Paste "Remove [SE] up to ranks in In the Know from checks to get information from people or disseminate news. Minion NPCs do not realize this character's allegiance in interviews." for Edit Description, press Save.

This is all I needed to do to fix the issue, but if you still have the problem you might need to go to the Propogandist Spec in the Data Editor and manually change the appropriate parts of the tree.

**Comment by nlx3647** [comment]
This was fixed by updating the talent ID.
