### ISSUE TITLE
Alchemist Specialization crashing Oggdude

### ISSUE THREAD

**Issue by icefyer** [nlx3647/dataset#25]
For whatever reason, selecting the Alchemist specialization with the imported dataset keeps throwing up an "unhandled exception. Object reference not set to an instance of an object" error.

**Comment by HighPriestofZuul** [comment]
This can be fixed relatively easily.

1. Open up the Data Editor (SWCharGenDataEditor)
2. In the bar on the left, select Specializations
3. Select the Alchemist Spec, select Modify
4. There's a blank box in the Talents tree, causing the crash. Change that to Alchemical Arts.
5. Update, Save, Done.

**Comment by nlx3647** [comment]
Just checked in the Data Editor, and in the XML file. I don't see any missing talents, and I just downloaded the zip, selected the Alchemist spec and no crashes. Closing this issue.
