### ISSUE TITLE
Steel Hand Adept not linked to Warrior career, selecting it causes crash

### ISSUE THREAD

**Issue by ARavenOfManyHats** [nlx3647/dataset#27]
Similar to the issue already reported about the Alchemist specialization, picking the Steel Hand Adept crashes the program. Additionally, it's not linked to the Warrior career, erroneously.

**Comment by ARavenOfManyHats** [comment]
These are easily fixed though. A talent box is blank in the spec tree, and should be changed to "Acklay's Scything Strike." This is done through the Data Editor. Also through the Data Editor, you can modify the Warrior career to include the Steel Hand Adept spec. Save and done.

**Comment by HighPriestofZuul** [comment]
Juyo Berserker has the same problem and the same fix, though the talent it needs to have put into the tree is Inner Peace.

**Comment by nlx3647** [comment]
I loaded up a freshly downloaded dataset in Ogg and I don't see this problem in either Steel Hand or Juyo.

**Comment by ARavenOfManyHats** [comment]
That's... weird. Maybe it's download corruption or something. I certainly have the latest.
