### ISSUE TITLE
Warrior Signature Abilities Broken

### ISSUE THREAD

**Issue by HighPriestofZuul** [nlx3647/dataset#28]
The Warrior Signature Abilities (Deadly Reputation and Unmatched Ferocity) both appear to be detached from the Warrior tree, and attempts to modify them lead to a crash in the data editor. Looks like the only solution is to redo both, though the specific powers I've looked at seem fine.

**Comment by nlx3647** [comment]
Checked in data editor, opens just fine. Checked the profession it's linked to, and it's Warrior.
