### ISSUE TITLE
Jedi key isn't consistent across datasets

### ISSUE THREAD

**Issue by nlx3647** [nlx3647/dataset#3]
<Key>JEDI</Key> in base

  <Key>JEDICAREER1</Key> in Dataset_clonewars

**Comment by Confirm4Crit** [comment]
@nlx3647 Would this issue and the Clone Solider issue cause issues with the spec picklist crashing when we pick these Careers? I tried to adjust the keys manually, didn't work out (I'm *just* starting this system now, so I maybe didn't clean up the keys well enough)

**Comment by nlx3647** [comment]
@Confirm4Crit it's the exact same issue. I've managed to clean all the issues, you can't fix it from the data editor, the text files need to be changed manually. I'll add a new commit this weekend.

**Comment by Confirm4Crit** [comment]
@nlx3647 Was the recent commit a fix? Haven't had a change to look. 
if so yayyy 🎊

**Comment by nlx3647** [comment]
Yes it is, give it a whirl, it doesn't crash for me.

Closing issue.
