### ISSUE TITLE
Several vehicles not available despite being included in the data

### ISSUE THREAD

**Issue by ARavenOfManyHats** [nlx3647/dataset#30]
For example, every single YT-series ship is not available to select, despite having XML files and the data having been imported correctly. Extremely bizarre.

**Comment by ARavenOfManyHats** [comment]
Additionally, custom vehicles I create disappear entirely. The XML's exist, but the vehicle refuses to appear.

**Comment by ARavenOfManyHats** [comment]
It also arbitrarily ends the list after the vehicles with names that begin with M.

**Comment by nlx3647** [comment]
If this is in Stock Vehicle, I suspect that's by design.

I looked in New, and all the YT's were in there, as well as ships past an M. If anything happens after that, it's probably an issue with the application and not the dataset.

**Comment by ARavenOfManyHats** [comment]
Application, then. Even in "New" I have the issues. Oh well.

**Comment by nlx3647** [comment]
Which version of the app do you have ?
