### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Jedifish** [nlx3647/dataset#4]
There is no data for Rise of the Seperatists. It all just refers to book and page numbers.

**Comment by nlx3647** [comment]
In the dataset in the Master branch there is not. Rise of the Separatists is included in the CloneWars dataset.
The CloneWars dataset is in the 2.3.4.0 branch.

**Comment by nlx3647** [comment]
That would be correct, noone's made those descriptions yet, I believe. If someone has, by all means, let me know where I can find it.

**Comment by nlx3647** [comment]
I'm going to close this, since OggDude has added the data, and I'll keep hunting for a dataset that contains the descriptions. However, that's not a problem with my dataset per se.
