### ISSUE TITLE
ItemDescriptors.xml is Talents?

### ISSUE THREAD

**Issue by woodwardj** [nlx3647/dataset#8]
Should ItemDescriptors.xml be full of talents?

**Comment by NateThompson114** [comment]
This should be fixed with my pull request and you can use my branch until its merged: https://github.com/NateThompson114/dataset/tree/develop

Please let me know if you find any issues.

**Comment by nlx3647** [comment]
It shouldn't be full of talents. I only noticed this as a mistake recently, apologies.
